---
name: idr0027-dickerson-chromatin/experimentA
version: 2

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes
  - name: Characteristics [Genotype]
    clientname: Genotype
    include: yes
  - name: Characteristics [Genomic Separation Of Operators]
    clientname: Genomic Separation Of Operators
    include: yes
  - name: Characteristics [Cell Identifier]
    clientname: Cell Identifier
    include: yes
  - name: Channels
    include: yes
  - name: Comment [Image File Type]
    clientname: Image File Type
    include: yes


######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
