---
name: idr0028-pascualvargas-rhogtpases/screenA
version: 3

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Control Type
    include: yes
  - name: Control Comments
    include: yes
  - name: Quality Control
    include: yes
  - name: Quality Control Comments
    include: yes

  - name: Channels
    include: yes
  - name: Comments
    include: yes

  - name: Has Phenotype
    include: yes
  - name: Phenotype Annotation Level
    include: yes


######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
      - name: Characteristics [Cell Line]
        clientname: Cell Line
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line/supplementary
      columns:
      - name: Characteristics Comments
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/sirna
      columns:
      - name: siRNA Pool Identifier
        include: yes
        omitempty: no
      - name: siRNA Pool Identifier
        clientname: siRNA Identifier
        clientvalue: ""
        include: yes
        omitempty: no

  - group:
      namespace: openmicroscopy.org/mapr/sirna/supplementary
      columns:
      - name: siRNA Library Name
        include: yes
      - name: Reagent Design Gene Annotation Build
        include: yes


  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Gene Identifier
        include: yes
        omitempty: no
      - name: Gene Identifier
        clientname: Gene Identifier URL
        clientvalue: http://www.ncbi.nlm.nih.gov/gene/{{ value|urlencode }}
        include: yes
      - name: Gene Symbol
        include: yes
        omitempty: no

  - group:
      namespace: openmicroscopy.org/mapr/gene/supplementary
      columns:
      - name: Gene Symbol Synonyms
        include: yes
      - name: Gene Annotation Comments
        include: yes
      - name: RefSeq Locus
        include: yes
      - name: RefSeq GI Number
        include: yes
      - name: Analysis Gene Annotation Build
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 1
        clientname: Phenotype
        include: yes
      - name: Phenotype 1 Term Name a
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 1 Term Accession a
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 1 Term Accession a
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes
      - name: Phenotype 1 Term Name b
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 1 Term Accession b
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 1 Term Accession b
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 2
        clientname: Phenotype
        include: yes
      - name: Phenotype 2 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 2 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 2 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 3
        clientname: Phenotype
        include: yes
      - name: Phenotype 3 Term Name a
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 3 Term Accession a
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 3 Term Accession a
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes
      - name: Phenotype 3 Term Name b
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 3 Term Accession b
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 3 Term Accession b
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 4
        clientname: Phenotype
        include: yes
      - name: Phenotype 4 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 4 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 4 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 5
        clientname: Phenotype
        include: yes
      - name: Phenotype 5 Term Name a
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 5 Term Accession a
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 5 Term Accession a
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes
      - name: Phenotype 5 Term Name b
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 5 Term Accession b
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 5 Term Accession b
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 6
        clientname: Phenotype
        include: yes
      - name: Phenotype 6 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 6 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 6 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 7
        clientname: Phenotype
        include: yes
      - name: Phenotype 7 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 7 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 7 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 8
        clientname: Phenotype
        include: yes
      - name: Phenotype 8 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 8 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 8 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 9
        clientname: Phenotype
        include: yes
      - name: Phenotype 9 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 9 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 9 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes


# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
      - Cell Line
    - namespace: openmicroscopy.org/mapr/sirna
      keys:
      - siRNA Identifier
      - siRNA Pool Identifier
    - namespace: openmicroscopy.org/mapr/gene
      keys:
      - Gene Identifier
      - Gene Symbol
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
      - Phenotype
