---
name: idr0023-szymborska-nuclearpore/experimentA
version: 2

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Experimental Condition [Targeted Protein]
    include: yes
  - name: Experimental Condition [Targeted Protein]
    clientname: Experimental Condition [Targeted Protein] URL
    clientvalue: http://www.ebi.ac.uk/pdbe/entry/search/index?text:{{ value }}
    include: yes

  - name: Gene Identifier
    include: yes
  - name: Gene Identifier
    clientname: Gene Identifier URL
    clientvalue: http://www.ensembl.org/id/{{ value }}
    include: yes
  - name: Gene Symbol
    include: yes
  - name: Gene Symbol Synonyms
    include: yes

  - name: Experimental Condition [Antibody]
    include: yes

  - name: Phenotype 1
    include: yes
  - name: Phenotype 1 Term Name
    include: yes
  - name: Phenotype 1 Term Accession
    include: yes
  - name: Phenotype 1 Term Accession
    clientname: Phenotype 1 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes

######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Gene Identifier
        include: yes
      - name: Gene Identifier
        clientname: Gene Identifier URL
        clientvalue: http://www.ensembl.org/id/{{ value }}
        include: yes
      - name: Gene Symbol
        include: yes
      - name: Gene Symbol Synonyms
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 1
        include: yes
      - name: Phenotype 1 Term Name
        include: yes
      - name: Phenotype 1 Term Accession
        include: yes
      - name: Phenotype 1 Term Accession
        clientname: Phenotype 1 Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

# Advanced options (experimental)
advanced:
     # If a map-annotation is attached to a well also attach it to all images
     # in the well
     well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/gene
      keys:
      - Compound Name
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
      - Phenotype
