---
name: idr0019-sero-nfkappab/screenA
version: 2

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Organism]
    clientname: Organism
    include: yes
  - name: Characteristics [Cell Line]
    clientname: Cell Line
    include: yes
  - name: Cell Type\Genetic Subtype (Neve et al., Cancer Cell 2006)
    include: yes
  - name: Experimental Condition [Media]
    clientname: Media
    include: yes
  - name: Experimental Condition [Compound]
    clientname: Compound
    include: yes
  - name: Experimental Condition [Dose]
    clientname: Dose
    include: yes
  - name: Experimental Condition [Time]
    clientname: Time
    include: yes

  - name: Control Type
    include: yes
  - name: Control Comments
    include: yes
  - name: Channels
    include: yes

  - name: Comments
    include: yes
  - name: Cell Line Morphotype
    include: yes
    
# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes
