---
name: idr0004-thorpe-rad52/screenA
version: 2

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes

  - name: Batch
    include: yes
  - name: Control Type
    include: yes
  - name: Control Comments
    include: yes
  - name: Quality Control
    include: yes
  - name: Channels
    include: yes
  - name: Comments
    include: yes
  - name: Author Hit
    include: yes
  - name: Has Phenotype
    include: yes
  - name: Phenotype Annotation Level
    include: yes


######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Gene Identifier
        include: yes
        omitempty: no
      - name: Gene Identifier
        clientname: Gene Identifier URL
        clientvalue: >
          https://www.yeastgenome.org/locus/{{ value|urlencode }}
        include: yes
      - name: Gene Symbol
        include: yes
        omitempty: no

  - group:
      namespace: openmicroscopy.org/mapr/gene/supplementary
      columns:
      - name: Gene Symbol Synonyms
        include: yes
      - name: Gene Description
        include: yes
      - name: GO Biological Process
        include: yes
      - name: GO Molecular Function
        include: yes
      - name: GO Cellular Component
        include: yes
      - name: GO Term
        include: yes
      - name: Reagent Design Gene Annotation Build
        include: yes
      - name: Analysis Gene Annotation Build
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 1
        clientname: Phenotype
        include: yes
      - name: Phenotype 1 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 1 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 1 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes


# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
    - namespace: openmicroscopy.org/mapr/gene
      keys:
      - Gene Identifier
      - Gene Symbol
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
      - Phenotype
