---
name: idr0017-breinig-drugscreen/screenA
version: 3

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Control Type
    include: yes
  - name: Control Comments
    include: yes
  - name: Channels
    include: yes

  - name: Has Phenotype
    include: yes
  - name: Phenotype Annotation Level
    include: yes


######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
      - name: Characteristics [Cell Line]
        clientname: Cell Line
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line/supplementary
      columns:
      - name: Mutation Detailed
      include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
      - name: Compound Name
        include: yes
      - name: Compound Name
        clientname: Compound Name URL
        clientvalue: https://www.ncbi.nlm.nih.gov/pccompound?term={{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound/supplementary
      columns:
      - name: Compound Treatment
        include: yes
      - name: Compound Secondary Name
        include: yes
      - name: Compound Class
        include: yes
      - name: Compound Enzyme
        include: yes
      - name: Compound Action
        include: yes
      - name: Compound Selectivity
        include: yes
      - name: Compound Description
        include: yes
      - name: Compound Selectivity Updated
        include: yes


# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
      - Cell Line
    - namespace: openmicroscopy.org/mapr/compound
      keys:
      - Compound Name
